# Enable CloudCannon CMS interface
cloudcannon:
  data: true

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Global upload directory for images
uploads_dir: /assets/images

# Paths
## Global permalinks
permalink: /:path

_comments:
  fundo: 'Escolha o fundo da seção entre as opções'
  description_text: 'Importante para o posicionamento nos sites de busca; utilizar palavras-chave e descrição do conteúdo em menos de 160 caracteres'
  

## Collections permalinks
collections:
  cursos:
    output: true
    permalink: /cursos/:title
  passeios:
    output: true
    permalink: /passeios/:title

defaults:
  -
    scope:
      path: "/cursos"
      type: "pages"
    values:
      layout: pages
      title:
      description_text:
      imagem_principal_image:
      chamada_principal:
      header_content_text:
      sections: 

# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-responsive-image

# Configuration of the jekyll-responsive-image plugin
responsive_image:
  template: _includes/templates/image-tag-lazy.html
  sizes:
    - width: 360
    - width: 480
    - width: 600
    - width: 800
    - width: 1400
  base_path: assets/images
  output_path_format: assets/images/srcset/%{width}/%{basename}

# Configuration of the jekyll-webp plugin    
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images/"]
  nested: true

icons:
 - "Facebook"  
 - "Instagram"
 - "YouTube"
 - "Email"

fundos:
  - "bg-light"
  - "bg-dark"
  - "bg-accent"

sections: []
_array_structures:
  sections:
    style: select
    values:
      - label: Overview
        description: Um parágrafo de abertura para a página
        icon: text
        value:
          _id: overview
          label: Overview
          cabecalho_html:
          texto_html:
          incluir_botao: false
          texto_botao:
          destino_botao_url:
      - label: Image Boxes
        description: Grid com imagens e descrição de conteúdo
        icon: text
        value:
          _id: image-boxes
          label: Image Boxes
          imagem_1_image:
          imagem_1_alt_text:
          cabecalho_1_html:
          paragrafo_1_html:
          imagem_2_image:
          imagem_2_alt_text:
          cabecalho_2_html:
          paragrafo_2_html:
      - label: Imagem e Texto
        description: Seção com uma imagem e espaço para texto
        icon: text
        value:
          _id: img-txt-1
          label: Imagem e Texto
          fundo:
          cabecalho_html:
          texto_html:
          imagem_image:
          imagem_alt_text:
          texto_botao:
          destino_botao_url: 